-- SQL para crear la tabla ProjectDocument en Informix
-- Esta tabla almacena los documentos de proyecto y sus atributos principales.

CREATE TABLE ProjectDocuments (
    Id SERIAL PRIMARY KEY,
    ProjectCode LVARCHAR(100) NOT NULL,
    ProjectName LVARCHAR(255) NOT NULL,
    Sponsor LVARCHAR(255),
    FunctionalLead LVARCHAR(255),
    TechnicalLead LVARCHAR(255),
    DocumentStatus LVARCHAR(100) NOT NULL,
    ProjectVision TEXT,
    GeneralObjective TEXT,
    SpecificObjectives TEXT,
    ExpectedValue TEXT,
    Scope TEXT,
    Exclusions TEXT,
    SolutionDescription TEXT,
    SolutionType TEXT,
    DeploymentModel TEXT,
    SoftwareStack TEXT,
    HardwareArchitecture TEXT,
    SecurityControl TEXT,
    ExpectedConcurrentUsers INTEGER,
    SlaResponseTime LVARCHAR(255),
    UseCases TEXT,
    RequiredDiagrams TEXT,
    ExperienceDesignMockups TEXT,
    TargetUsers TEXT,
    EstimatedBudget LVARCHAR(255),
    TargetDate DATETIME YEAR TO SECOND,
    TechnicalConstraints TEXT,
    BusinessConstraints TEXT,
    RegulationsCompliance TEXT,
    InvolvedAreas TEXT,
    OrganizationalImpact TEXT,
    MasterDataMigration TEXT,
    ResponsibilitiesSummary TEXT,
    ChangeManagementAdoption TEXT,
    OperationSupport TEXT,
    CreatedBy LVARCHAR(255) NOT NULL,
    Identification LVARCHAR(255) NOT NULL,
    Username LVARCHAR(255) NOT NULL,
    CreatedAt DATETIME YEAR TO SECOND NOT NULL,
    UpdatedAt DATETIME YEAR TO SECOND,
    IsActive BOOLEAN NOT NULL
);
